import { Recipe } from './types';

export const INITIAL_RECIPES: Recipe[] = [
  {
    id: '1',
    title: 'מאפינס שוקולד קסומים',
    description: 'מאפינס רכים ונימוחים שכיף להכין עם חברים. מלאים בשוקולד צ\'יפס!',
    category: 'אפייה',
    difficulty: 'קל',
    timeMinutes: 45,
    ingredients: [
      { item: 'קמח', amount: '2 כוסות' },
      { item: 'סוכר', amount: '1 כוס' },
      { item: 'קקאו', amount: '1/2 כוס' },
      { item: 'שוקולד צ\'יפס', amount: '1 כוס' },
      { item: 'ביצים', amount: '2' },
      { item: 'שמן', amount: '1/2 כוס' },
    ],
    instructions: [
      'מחממים תנור ל-180 מעלות.',
      'מערבבים את כל היבשים בקערה אחת.',
      'מערבבים את כל הרטובים בקערה שנייה.',
      'מאחדים בין הקערות ומערבבים רק עד שאין גושים.',
      'ממלאים תבניות מאפינס ואופים כ-20 דקות.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1582716401301-b2407dc7563d?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '2',
    title: 'פסטה ברוטב עגבניות סודי',
    description: 'ארוחת צהריים מהירה וטעימה שילדים ומבוגרים אוהבים.',
    category: 'בישול',
    difficulty: 'קל',
    timeMinutes: 20,
    ingredients: [
      { item: 'פסטה', amount: 'חבילה אחת' },
      { item: 'עגבניות מרוסקות', amount: '1 קופסה' },
      { item: 'שום', amount: '2 שיניים' },
      { item: 'בזיליקום', amount: 'חופן' },
      { item: 'שמן זית', amount: '2 כפות' },
    ],
    instructions: [
      'מבשלים את הפסטה לפי הוראות היצרן.',
      'במחבת נפרדת מטגנים קלות את השום בשמן זית.',
      'מוסיפים את העגבניות והתבלינים ומבשלים 10 דקות.',
      'מערבבים את הפסטה עם הרוטב ומגישים חם.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '3',
    title: 'שניצלונים פריכים במיוחד',
    description: 'רצועות עוף בציפוי זהוב וקריספי. הכי טעים עם קטשופ!',
    category: 'טיגון',
    difficulty: 'בינוני',
    timeMinutes: 40,
    ingredients: [
      { item: 'חזה עוף', amount: '500 גרם' },
      { item: 'פירורי לחם', amount: '2 כוסות' },
      { item: 'ביצים', amount: '2' },
      { item: 'קמח', amount: '1 כוס' },
      { item: 'שמן לטיגון', amount: 'לפי הצורך' },
    ],
    instructions: [
      'חותכים את העוף לרצועות.',
      'מכינים 3 צלחות: קמח, ביצה טרופה, ופירורי לחם.',
      'טובלים כל רצועה בקמח, בביצה ולבסוף בפירורים.',
      'מטגנים בשמן חם עד להזהבה משני הצדדים.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '4',
    title: 'פיצה פיתה מהירה',
    description: 'הפיצה הכי קלה בעולם! מושלמת לנשנוש של אחה"צ.',
    category: 'אפייה',
    difficulty: 'קל',
    timeMinutes: 10,
    ingredients: [
      { item: 'פיתה', amount: '1' },
      { item: 'רסק עגבניות', amount: '2 כפות' },
      { item: 'גבינה צהובה', amount: '2 פרוסות' },
      { item: 'זיתים', amount: 'לפי הטעם' },
      { item: 'אורגנו', amount: 'קורט' },
    ],
    instructions: [
      'חוצים את הפיתה לשני עיגולים.',
      'מורחים רסק עגבניות על כל חלק.',
      'מפזרים גבינה צהובה ותוספות שאוהבים.',
      'מכניסים לטוסטר אובן או לתנור ל-5 דקות עד שהגבינה נמסה.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '5',
    title: 'פנקייקים בצורות',
    description: 'ארוחת בוקר של אלופים. נסו לצייר עם הבלילה במחבת!',
    category: 'טיגון',
    difficulty: 'בינוני',
    timeMinutes: 25,
    ingredients: [
      { item: 'קמח', amount: '1 כוס' },
      { item: 'חלב', amount: '1 כוס' },
      { item: 'ביצה', amount: '1' },
      { item: 'סוכר', amount: '2 כפות' },
      { item: 'אבקת אפייה', amount: '1 כפית' },
    ],
    instructions: [
      'מערבבים את כל המצרכים בקערה עד לקבלת בלילה חלקה.',
      'משמנים מחבת במעט חמאה או שמן.',
      'יוצקים עיגולים קטנים (או צורות!) למחבת.',
      'כשיש בועות, הופכים לצד השני לדקה נוספת.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '6',
    title: 'שיפודי פירות מרעננים',
    description: 'קינוח בריא וצבעוני. פשוט להשחיל ולאכול!',
    category: 'בישול',
    difficulty: 'קל',
    timeMinutes: 15,
    ingredients: [
      { item: 'ענבים', amount: 'חופן' },
      { item: 'תותים', amount: '5-6' },
      { item: 'מלון', amount: 'פרוסה עבה' },
      { item: 'מרשמלו', amount: 'אופציונלי' },
    ],
    instructions: [
      'שוטפים היטב את הפירות.',
      'חותכים את המלון לקוביות גדולות.',
      'משחילים על שיפוד עץ בסדר צבעוני: ענב, תות, מלון.',
      'מגישים צונן.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1490818387583-1baba5e638af?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '7',
    title: 'חביתה מקושקשת של שפים',
    description: 'הסוד לחביתה הכי טעימה בעולם הוא ערבוב מתמיד.',
    category: 'טיגון',
    difficulty: 'קל',
    timeMinutes: 5,
    ingredients: [
      { item: 'ביצים', amount: '2' },
      { item: 'חלב', amount: '1 כף' },
      { item: 'מלח', amount: 'קורט' },
      { item: 'חמאה', amount: 'קוביה קטנה' },
    ],
    instructions: [
      'טורפים את הביצים עם החלב והמלח בקערה.',
      'ממיסים חמאה במחבת על אש בינונית.',
      'שופכים את הביצים ומערבבים בעדינות עם כף עץ כל הזמן.',
      'מורידים מהאש כשהביצים עדיין מעט רטובות.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '8',
    title: 'כדורי שוקולד (בלי תנור)',
    description: 'הקינוח הכי טעים וקל להכנה, רק לערבב ולגלגל.',
    category: 'אפייה',
    difficulty: 'קל',
    timeMinutes: 30,
    ingredients: [
      { item: 'ביסקוויטים', amount: 'שרוול (250 גרם)' },
      { item: 'שוקולד למריחה', amount: '3 כפות גדושות' },
      { item: 'חלב', amount: '1/3 כוס' },
      { item: 'קוקוס', amount: 'לציפוי' },
    ],
    instructions: [
      'מרסקים את הביסקוויטים לפירורים דקים בתוך שקית או קערה.',
      'מוסיפים את השוקולד והחלב לקערה עם הפירורים.',
      'מערבבים היטב עם הידיים עד שנוצר בצק שוקולדי.',
      'יוצרים כדורים קטנים ומגלגלים אותם בקוקוס.',
      'שומרים במקרר עד שאוכלים.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1590080875515-8a03b1447070?auto=format&fit=crop&q=80&w=800',
  }
];